git:
  commitMessage: "[chore] Release v${version}"
  requireBranch:
    - main
    - next
github:
  release: true
  web: true
  releaseName: "${version}: "
npm:
  publish: true
hooks:
  before:init:
    - task test build
  after:release: "echo Successfully released ${name} v${version} to ${repo.repository} and NPM."
